import Head from "next/head";
import { useState } from "react";
import { useForm, useFieldArray } from "react-hook-form";
import { Entidades } from "../components/Entidades";

import styles from "../styles/Home.module.css";

export default function Home() {
	const {
		control,
		register,
		formState: { errors },
		handleSubmit,
	} = useForm();
	const onSubmit = (data) => console.log(data.foto[0]);

	

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div className="flex flex-col justify-between">
					<form onSubmit={handleSubmit(onSubmit)}>
						<div className="flex flex-col">
							<div>
								<label className="w-full font-bold">Foto/Imagen </label>
								
								<input
                                    type="file"
                                    { ...register("foto")}
									className="w-full border-2 mt-2"
								/>
							</div>
						</div>

						<div className="flex justify-center items-center mt-4">
							<button
								type="submit"
								className="mt-2 bg-red-700 text-white px-12 py-2 w-full rounded-full"
							>
								Guardar
							</button>
						</div>
					</form>
				</div>
			</main>
		</div>
	);
}
