import Head from "next/head";
import { useState } from "react";
import { useForm } from "react-hook-form";

import styles from "../styles/Home.module.css";

export default function Home() {
	const {  register, watch, formState: { errors }, handleSubmit } = useForm();
	const onSubmit = (data) => console.log(data);
	const [showCamp, setShowCamp] = useState(false);
	const [showCampNatural, setShowCampNatural] = useState(false);

	const tipopersona = register("tipopersona");

	const selectedTipopersona = () =>{
		const tipopersonaSelected = watch("tipopersona");
        console.log("🚀 ~ file: index.js ~ line 19 ~ selectedTipopersona ~ tipopersonaSelected", tipopersonaSelected)
       	tipopersonaSelected === 'juridica' && setShowCamp(true);
		
		tipopersonaSelected === 'natural' && setShowCampNatural(true);
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>				
				<div className="flex flex-col justify-between">
					<form onSubmit={handleSubmit(onSubmit)}>
					<select
						className="px-12 py-2 mr-2  border-2"
						onChange={(e) => {
							tipopersona.onChange(e);
							selectedTipopersona();
						}}
						ref={tipopersona.ref}
						name="tipopersona"
					>
						<option value="">seleccione un tipo de persona</option>
						<option value="natural">Natural</option>
						<option value="juridica">Juridica</option>						
					</select>
						<br/>

						<div className={`${showCamp ? "block": "hidden"}`}>
							<label>razon social</label>
						</div>

						<div className={`${showCampNatural ? "block": "hidden"}`}>
							<label>nombre </label>
						</div>
						<div className={`${showCampNatural ? "block": "hidden"}`}>
							<label>apellido</label>
						</div>
						<div className="flex justify-center items-center">
							<button type="submit"  className="mt-2 bg-red-700 text-white px-12 py-2 w-full rounded-full">
								Guardar
							</button>
						</div>
					</form>
				</div>
			</main>
		</div>
	);
}
